---
- hosts: openvpn
  sudo: true
  tasks:
    - name: check tunnel statuss
      shell: pgrep -f {{_node_number}}_{{_cluster_id}} || grep -v pgrep
      register: result
    - debug: var=result.stdout_lines      
      
  
 
          



