---


- hosts: openvpn
  gather_facts: no
  sudo: yes
  tasks:
    - name: dump facts to file
      local_action: copy content='{{ hostvars | to_nice_json}}' dest="/mount/ansibledata/{{_cluster_id}}/vars/inventory_{{_cluster_id }}.json"
      sudo: false
    - name: call create container
      shell: ruby /mount/ansible/templates/cluster/openvpn/create_node.rb  {{_cluster_id}} {{_node_number}} {{_node_name}} {{_openvpn_ip_address}}

- hosts: provisioner
  gather_facts: no
  tasks:
    - name: call create container
      shell: ruby /mount/ansible/templates/cluster/provisioner/create_node.rb  {{_cluster_id}} {{_node_number}} {{_node_name}} {{_openvpn_ip_address}}


