---

- hosts: provisioner
  gather_facts: no
  pre_tasks:
    - name: dump facts to file
      local_action: copy content='{{ hostvars | to_nice_json}}' dest="/mount/ansibledata/{{_cluster_id}}/vars/inventory_{{_cluster_id }}.json"
      sudo: false
  tasks:
    - name: call ruby
      shell: ruby /mount/ansible/templates/cluster/provisioner/create_node_first.rb {{_cluster_id}}


- hosts: openvpn
  gather_facts: no
  sudo: yes
  tasks:
    - name: call create node ruby script
      shell: ruby /mount/ansible/templates/cluster/openvpn/create_node.rb  {{_cluster_id}}

- hosts: provisioner
  gather_facts: no
  tasks:
    - name: call create node ruby script
      shell: ruby /mount/ansible/templates/cluster/{{name}}/create_node.rb  {{_cluster_id}}
