---
- hosts: local
  gather_facts: no
  tasks:
    - name: create container directory
      file: path="clusters/{{ _cluster_name }}" state=directory 
    - name: create container directory
      file: path="clusters/{{ _cluster_name }}/vagrant" state=directory  mode=0775
              
- hosts: master
  gather_facts: no
  sudo: true
                
  roles:
    - run_hadoop_container_on_master
    - run_hue_container_on_master                  
#### proxy
- hosts: proxy
  gather_facts: no
  vars:
    _source_port: "{{_port_hadoop_ssh}}"
    _destination_host: "hadoop-master-{{_cluster_id}}.gex"
    _destination_port: 22
  sudo: true
  roles:
    - create_proxy


#### webproxy

- hosts: webproxy
  gather_facts: no
  sudo: true
  pre_tasks:
    - set_fact:
        _hadoop_ipv4: "51.77.{{ ((_cluster_id|int ) // 256) | int}}.{{ ((_cluster_id|int ) % 256) | int}}"
        _hue_ipv4: "51.78.{{ ((_cluster_id|int ) // 256) | int}}.{{ ((_cluster_id|int ) % 256) | int}}"
  roles:
    - create_webproxy
      
        
        


