---
#### webproxy

- hosts: webproxy
  gather_facts: no
  sudo: true
  pre_tasks:
    - set_fact:
        _hadoop_ipv4: "51.77.{{ ((_cluster_id|int ) // 256) | int}}.{{ ((_cluster_id|int ) % 256) | int}}"
        _hue_ipv4: "51.78.{{ ((_cluster_id|int ) // 256) | int}}.{{ ((_cluster_id|int ) % 256) | int}}"
  roles:
    - create_webproxy
      
