---


- hosts: master
  gather_facts: no
  sudo: true
  tasks:
    - name: create vars directory if not exists
      file: path="/mount/ansibledata/{{_cluster_id}}/vars" state=directory  mode=0775
    - name: dump facts to file
      local_action: copy content='{{ hostvars | to_nice_json}}' dest="/mount/ansibledata/{{_cluster_id}}/vars/inventory_{{_cluster_id }}.json"
      sudo: false
    - name: call remove container
      shell: ruby /mount/ansible/templates/cluster/master/remove_cluster.rb {{_cluster_id}}




- hosts: proxy
  gather_facts: no
  sudo: true

  tasks:
    - name: call remove container
      shell: ruby /mount/ansible/templates/cluster/proxy/remove_cluster.rb {{_cluster_id}}

- hosts: webproxy
  gather_facts: no
  sudo: true
  tasks:
    - name: call remove container
      shell: ruby /mount/ansible/templates/cluster/webproxy/remove_cluster.rb {{_cluster_id}}


- hosts: openvpn
  gather_facts: no
  sudo: true
  tasks:
    - name: call remove container
      shell: ruby /mount/ansible/templates/cluster/openvpn/remove_cluster.rb {{_cluster_id}}

- hosts: provisioner
  gather_facts: no
  roles:
    - { role: destroy_aws_cluster, when: _cluster_type is defined and _cluster_type == "aws" }
  tasks:
    - name: call remove cluster
      shell: ruby /mount/ansible/templates/cluster/provisioner/remove_cluster.rb {{_cluster_id}}
