source 'https://rubygems.org'

#ruby "2.3.3"

gem 'json'


gem 'capistrano',  '3.7.1'
#gem 'capistrano-rails', '1.1.7'
#gem 'capistrano-rails', '1.1.3'
gem 'capistrano-bundler', '1.1.4'
gem 'capistrano-rvm',   '0.1.2'

#gem 'capistrano-locally'
#gem 'capistrano-passenger'
#gem 'capistrano-touch-linked-files'
#gem 'capistrano-upload-config'

gem 'slackistrano'




