source "https://rubygems.org"


gem "rack"
gem "json"
gem "unicorn"

group :development do
  gem "guard-process"
  gem "awesome_print"
  gem "travis-lint"
end

group :test do
  gem "minitest"
  gem "rake"
  gem "rack-test"
  gem "simplecov"
end
