#! /usr/bin/env ruby
#  encoding: UTF-8
require 'aws-sdk'

ENV["VAGRANT_DEFAULT_PROVIDER"]="virtualbox"

FILES_MAIN_IP = "51.0.1.6"
FILES_DEV_IP = "51.0.12.6"
MASTER_HOST_MAIN_IP = "51.1.0.50"
MASTER_HOST_DEV_IP = "51.1.0.50"
MASTER_HOST_PROD_IP = "104.247.220.90"

DIR_NAME = '/var/www/html'
SSH_ADDRESS_FILES_MAIN = "vagrant@#{FILES_MAIN_IP}"
SSH_ADDRESS_FILES_DEV = "vagrant@#{FILES_DEV_IP}"


SSH_ADDRESS_MASTER_MAIN = "gex@#{MASTER_HOST_MAIN_IP}"
SSH_ADDRESS_MASTER_DEV = "gex@#{MASTER_HOST_DEV_IP}"
SSH_ADDRESS_MASTER_PROD = "gex@#{MASTER_HOST_PROD_IP}"


LOCAL_PREFIX_MAIN = "http://#{FILES_MAIN_IP}"
LOCAL_PREFIX_DEV = "http://#{FILES_DEV_IP}"
REMOTE_ADDRESS = 'files.galacticexchange.io'
LOCAL_PASSWORD = 'vagrant'
LOCAL_PASSWORD_MASTER = 'PH_GEX_PASSWD1'
PROD_PASSWORD_MASTER = 'PH_GEX_PASSWD3#'
LOCAL_CONTAINER_URL_DEV = LOCAL_PREFIX_DEV + "/containers/"
LOCAL_BOX_URL_DEV = LOCAL_PREFIX_DEV + "/boxes/"
LOCAL_CONTAINER_URL_MAIN = LOCAL_PREFIX_MAIN + "/containers/"
LOCAL_BOX_URL_MAIN = LOCAL_PREFIX_MAIN + "/boxes/"


CONTAINER_DIR= DIR_NAME + '/containers'
BOX_DIR= DIR_NAME + '/boxes'
CLOUDFRONT_IDS = {'clustergx-iso' => 'E2D1AQHH4KWP3Q', 'gex-boxes' => 'E5AGWVBUXNOML', 'gex-containers' => 'E2O3NCM6YLLH09', 'gex-debian' => 'E3AER9RGJ7UJH9'}

ACCESS_KEY_ID = 'PH_GEX_KEY_ID'
SECRET_ACCESS_KEY = 'PH_GEX_ACESS_KEY'